### ISSUE TITLE
How to run the project

### ISSUE THREAD

**Issue by Sundy3366** [deepfunc/react-test-demo#2]
你好， 
  请问如何运行这个项目？

**Comment by Sundy3366** [comment]
我尝试用npm start 无法启动项目

**Comment by deepfunc** [comment]
首先 `npm install` 安装依赖
如果是想跑测试的话，执行 `npm test`
如果是想跑这个 demo 演示的话：
* 先执行 `npm run start-dev`，这个是启动 `webpack-dev-server`
* 上一个执行完后不要关命令行，再开一个执行 `npm run start-server`，这个是启动 `node`
* 然后浏览器访问 `http://localhost:3000` 就行了

觉得不错给个 star 哈，谢谢了
